// import "./src/day1/index";
// import "./src/day2/index";
// import "./src/day3/index";
// import "./src/day4/index";
// import "./src/day5/index";
// import "./src/day6/index";
// import "./src/day7/index";
// import "./src/day8/index";
// import "./src/day9/index";
import "./src/day10/index";
